version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    groups:
      cargo-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
    exclude-paths:
      - .github/workflows/release.yml
