ignore = [".devenv", "target"]

[modules.typst-pack]
source = "."
entrypoint = true

[modules.tests]
source = ".dagger/modules/tests"

[modules.rust]
source = "github.com/sagikazarmark/daggerverse-beta/rust"

[modules.rust.settings]
version = "1.97-slim-trixie"

[modules.dagger-gha]
source = "github.com/sagikazarmark/daggerverse-beta/dagger-gha"

[modules.dagger-gha.settings]
daggerCommit = "86d1d2f5791bcf3213d56903cfa81a3ba0abe54a"
lock = '"PINNED"'

[modules.dang]
source = "github.com/sagikazarmark/daggerverse-beta/dang"
